name: Deploy API server

on:
  push:
    branches:
      - staging
      - staging-api
  workflow_dispatch:

env:
  REGION: "${{ vars.STAGING_GCP_REGION }}"
  SERVICE: "${{ vars.STAGING_GCP_SERVICE_NAME_API }}"
  PROJECT_ID: "${{ vars.STAGING_GCP_PROJECT_ID }}"
  SERVICE_ACCOUNT: "${{ secrets.STAGING_GCP_SERVICE_ACCOUNT }}"
  WIF_PROVIDER: "${{ secrets.STAGING_WIF_PROVIDER }}"
  CMS_PAYLOAD_URL: ${{ vars.STAGING_CMS_PAYLOAD_URL }}
  CMS_PAYLOAD_LOGIN_EMAIL: ${{ secrets.STAGING_CMS_PAYLOAD_LOGIN_EMAIL }}
  CMS_PAYLOAD_LOGIN_PASSWORD: ${{ secrets.STAGING_CMS_PAYLOAD_LOGIN_PASSWORD }}

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Dockerfile
        run: cp ./apps/api/Dockerfile .

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: "${{ env.SERVICE_ACCOUNT }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          flags: "--platform=managed --min-instances=0 --allow-unauthenticated"
          # Update to the appropriate source folder
          source: ./
          env_vars: |-
            CMS_PAYLOAD_URL=${{ env.CMS_PAYLOAD_URL }}
            CMS_PAYLOAD_LOGIN_EMAIL=${{ env.CMS_PAYLOAD_LOGIN_EMAIL }}
            CMS_PAYLOAD_LOGIN_PASSWORD=${{ env.CMS_PAYLOAD_LOGIN_PASSWORD }}
