name: Deploy API server

on:
  push:
    branches:
      - staging
      - staging-api
  workflow_dispatch:

env:
  REGION: "${{ vars.STAGING_GCP_REGION }}"
  SERVICE: "${{ vars.STAGING_GCP_SERVICE_NAME_API }}"
  PROJECT_ID: "${{ vars.STAGING_GCP_PROJECT_ID }}"
  SERVICE_ACCOUNT: "${{ secrets.STAGING_GCP_SERVICE_ACCOUNT }}"
  WIF_PROVIDER: "${{ secrets.STAGING_WIF_PROVIDER }}"
  CMS_PAYLOAD_URL: ${{ vars.STAGING_CMS_PAYLOAD_URL }}
  CMS_PAYLOAD_LOGIN_EMAIL: ${{ secrets.STAGING_CMS_PAYLOAD_LOGIN_EMAIL }}
  CMS_PAYLOAD_LOGIN_PASSWORD: ${{ secrets.STAGING_CMS_PAYLOAD_LOGIN_PASSWORD }}
  AWS_REGION: "${{ vars.STAGING_AWS_REGION }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}"
  AWS_S3_ENDPOINT: "${{ vars.STAGING_AWS_S3_ENDPOINT }}"
  AWS_S3_BUCKET: "${{ vars.STAGING_AWS_S3_BUCKET }}"
  AWS_S3_AUTH_METHOD: "${{ vars.STAGING_AWS_S3_AUTH_METHOD }}"
  R2_URL: "${{ vars.STAGING_R2_URL }}"
  HTTP_BASIC_AUTH: "${{ vars.STAGING_HTTP_BASIC_AUTH }}"
  HTTP_BASIC_AUTH_USERNAME: "${{ vars.STAGING_HTTP_BASIC_AUTH_USERNAME }}"
  HTTP_BASIC_AUTH_PASSWORD: "${{ vars.STAGING_HTTP_BASIC_AUTH_PASSWORD }}"
  SERVICE_STORAGE: "${{ vars.STAGING_SERVICE_STORAGE }}"

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Dockerfile
        run: cp ./apps/api/Dockerfile .

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ env.WIF_PROVIDER }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          flags: "--platform=managed --min-instances=0 --allow-unauthenticated"
          # Use the appropriate source folder
          source: ./
          env_vars: |-
            CMS_PAYLOAD_URL=${{ env.CMS_PAYLOAD_URL }}
            CMS_PAYLOAD_LOGIN_EMAIL=${{ env.CMS_PAYLOAD_LOGIN_EMAIL }}
            CMS_PAYLOAD_LOGIN_PASSWORD=${{ env.CMS_PAYLOAD_LOGIN_PASSWORD }}
            AWS_REGION=${{ env.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_ENDPOINT=${{ env.AWS_S3_ENDPOINT }}
            AWS_S3_BUCKET=${{ env.AWS_S3_BUCKET }}
            AWS_S3_AUTH_METHOD=${{ env.AWS_S3_AUTH_METHOD }}
            R2_URL=${{ env.R2_URL }}
            HTTP_BASIC_AUTH=${{ env.HTTP_BASIC_AUTH }}
            HTTP_BASIC_AUTH_USERNAME=${{ env.HTTP_BASIC_AUTH_USERNAME }}
            HTTP_BASIC_AUTH_PASSWORD=${{ env.HTTP_BASIC_AUTH_PASSWORD }}
            SERVICE_STORAGE=${{ env.SERVICE_STORAGE }}
